Repository photoview/photoview.github.io, pull requests merged in 2024-07, with the labels that each got.

#28 Link to the post, how to install Photoview on FreeBSD
  .gitignore
  src/en/docs/installation-manual.md
Labels: documentation, enhancement

#29 usage-basic-overview.md
  package-lock.json
  package.json
  src/assets/images/screenshot-manage-person.png
  src/assets/images/screenshot-map-oneset.png
  src/assets/images/screenshot-map-twoset.png
  src/assets/images/screenshot-maps2.png
  src/assets/images/screenshot-protected-share.png
  src/assets/images/screenshot-unlabelled-people.png
  src/en/docs/usage-basic-overview.md
  src/en/docs/usage-people.md
  src/en/docs/usage-places.md
  src/en/docs/usage-sharing.md
  src/search-data.11ty.js
Labels: documentation, good first issue

#32 Fixing the documentation site layout
  package-lock.json
  package.json
  src/search-data.11ty.js
Labels: bug
